# Generated by Django 3.2.11 on 2022-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
