# Generated by Django 3.2.11 on 2022-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0003_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
