# Generated by Django 3.2.11 on 2022-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0004_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('text_date', models.CharField(blank=True, max_length=20, null=True)),
                ('t_time', models.TimeField()),
                ('phone_text', models.CharField(max_length=12)),
                ('booking_message', models.CharField(max_length=200)),
            ],
        ),
    ]
