# Generated by Django 3.2.11 on 2022-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0007_auto_20220202_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
