# Generated by Django 3.2.11 on 2022-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0008_alter_appointment_booking_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
