# Generated by Django 3.2.11 on 2022-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0009_alter_appointment_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_booking',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_booking',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
