# Generated by Django 3.2.11 on 2022-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0010_auto_20220202_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
