# Generated by Django 3.2.11 on 2022-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0011_alter_booking_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_text',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='t_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='text_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
