# Generated by Django 3.2.11 on 2022-02-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0013_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
