# Generated by Django 3.2.11 on 2022-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0014_rename_details_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='media')),
                ('story', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
