# Generated by Django 3.2.11 on 2022-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0015_discover_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='media')),
                ('service_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('service_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
