# Generated by Django 3.2.11 on 2022-02-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0016_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='service1_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_heading',
            new_name='service1_heading',
        ),
        migrations.RemoveField(
            model_name='discover_story',
            name='background',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.AddField(
            model_name='service',
            name='service2_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service2_heading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service3_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service3_heading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
