# Generated by Django 3.2.11 on 2022-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0017_auto_20220204_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('menu1', models.ImageField(upload_to='media')),
                ('menu2', models.ImageField(upload_to='media')),
                ('menu3', models.ImageField(upload_to='media')),
                ('menu4', models.ImageField(upload_to='media')),
            ],
        ),
    ]
