# Generated by Django 3.2.11 on 2022-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0018_discover_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_selling_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='media')),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_details', models.CharField(blank=True, max_length=150, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
