# Generated by Django 3.2.11 on 2022-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0020_main_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_dish',
            name='dish_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
