# Generated by Django 3.2.11 on 2022-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0021_alter_main_dish_dish_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_saying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_profession', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
