# Generated by Django 3.2.11 on 2022-02-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0022_customer_saying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_saying',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
