# Generated by Django 3.2.11 on 2022-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0024_about_us_our_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
