# Generated by Django 3.2.8 on 2022-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0027_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='person_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
