# Generated by Django 3.2.8 on 2022-02-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0029_remove_comment_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='media')),
                ('date', models.CharField(max_length=10)),
                ('blog_heading', models.CharField(max_length=30)),
                ('blog_description', models.CharField(max_length=500)),
            ],
        ),
    ]
