# Generated by Django 3.2.8 on 2022-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0030_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='writer',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
