# Generated by Django 3.2.11 on 2022-02-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0032_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_dish',
        ),
    ]
