# Generated by Django 3.2.11 on 2022-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0033_delete_main_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
