# Generated by Django 3.2.11 on 2022-02-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0034_auto_20220213_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('total_items', models.IntegerField(default=0)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Item_description', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
