# Generated by Django 3.2.11 on 2022-02-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0035_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_items',
            new_name='total',
        ),
    ]
