# Generated by Django 3.2.11 on 2022-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0036_rename_total_items_cartitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSubTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
