# Generated by Django 3.2.11 on 2022-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0038_billing_details_temp_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
