# Generated by Django 3.2.11 on 2022-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeshop_App', '0043_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Product_detail',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Product_photo',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Product_price',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
