# Generated by Django 3.2.11 on 2022-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_image', models.ImageField(upload_to='media')),
                ('dessert_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dessert_descripion', models.CharField(blank=True, max_length=30, null=True)),
                ('dessert_price', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_image', models.ImageField(upload_to='media')),
                ('drinks_name', models.CharField(blank=True, max_length=30, null=True)),
                ('drinks_descripion', models.CharField(blank=True, max_length=30, null=True)),
                ('drinks_price', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mainDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish_image', models.ImageField(upload_to='media')),
                ('main_dish_name', models.CharField(blank=True, max_length=30, null=True)),
                ('main_dish_descripion', models.CharField(blank=True, max_length=30, null=True)),
                ('main_dish_price', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_dish_image', models.ImageField(upload_to='media')),
                ('starter_name', models.CharField(blank=True, max_length=30, null=True)),
                ('starter_descripion', models.CharField(blank=True, max_length=30, null=True)),
                ('starter_price', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
