# Generated by Django 3.2.8 on 2022-02-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_app', '0002_auto_20220211_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindish',
            old_name='main_dish_descripion',
            new_name='main_dish_description',
        ),
    ]
