# Generated by Django 3.2.8 on 2022-02-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_app', '0003_rename_main_dish_descripion_maindish_main_dish_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drinks_descripion',
            new_name='drinks_descrtipion',
        ),
    ]
