# Generated by Django 3.2.8 on 2022-02-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_app', '0004_rename_drinks_descripion_drinks_drinks_descrtipion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='dessert_descripion',
            new_name='dessert_descrtipion',
        ),
    ]
